theme: minima
title: The most powerful power bank in the word
author: Alex Wong
email: alex0972112871@gmail.com
description: > # this means to ignore newlines until "baseurl:"
The biggest capacity in the world - 27,000 mAh
The smallest cube among all the same type power bank
The highest charging and recharging speed

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
